### ISSUE TITLE
Bug: Extension causes Google image search to not render results.

### ISSUE THREAD

**Issue by fahran** [Spetnik/W3Schools-Hider#1]
To reproduce:
1. Go to http://images.google.com
2. Search for something (e.g. house)
3. Modify search term (e.g. house blue) and search again (either click the magnifying glass or hit enter).

Google image search displays no results. Results appear when the view is re-sized, or the page is refreshed.

Behaviour ceases when W3Schools-Hider is disabled, and returns when re-enabled.

Thanks for the app, by the way - I do love it :D

**Comment by Spetnik** [comment]
Fixed
