### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by crisbeto** [Spetnik/W3Schools-Hider#2]
The extension seems to be broken for a while now, w3schools has started to creep back into searches:
![screenshot_1](https://cloud.githubusercontent.com/assets/4450522/9435345/4c3b3a02-4a47-11e5-8149-959e91d38dc8.png)

**Comment by crisbeto** [comment]
Hey @Spetnik could you take a look at this PR? https://github.com/Spetnik/W3Schools-Hider/pull/3 it should fix the issues with the results not being hidden.

**Comment by vinkla** [comment]
I can confirm this as well.

<img width="682" alt="screen shot 2015-10-15 at 13 04 04" src="https://cloud.githubusercontent.com/assets/499192/10511982/6fc632e6-733d-11e5-9f32-1252edd87578.png">

**Comment by crisbeto** [comment]
I don't think this project is being supported anymore, I submitted my PR with the fix 2 months ago and there's still no reply.

**Comment by vinkla** [comment]
Yeah probably, also just two commits ever made.

**Comment by Spetnik** [comment]
Sorrry! I've been swamped. I plan on updating it soon!

AJS

**Comment by vinkla** [comment]
![awesome](http://i.giphy.com/Qh6NZWsFx1G1O.gif)

**Comment by Spetnik** [comment]
Haha. Trust me, if you think it annoys you to see W3Schools in your Google
results, think about how much it must annoy me: the guy who was actually
bothered to the point where he had to write browser extensions to remove
it! 😛

**Comment by vinkla** [comment]
Haha, that is true :)

**Comment by crisbeto** [comment]
The struggle is real.

**Comment by Spetnik** [comment]
The extension has been fixed. Sorry about the delay!

**Comment by vinkla** [comment]
Awesome!

**Comment by crisbeto** [comment]
Nice, I'll go ahead and close my PR.
