### ISSUE TITLE
Update permissions

### ISSUE THREAD

**Issue by vinkla** [Spetnik/W3Schools-Hider#4]
Is it really necessary to _read and change all your data on the websites that you visit_? Maybe we can limit this to only `google.*` domains?

<img width="303" alt="screen shot 2016-10-27 at 7 14 25 am" src="https://cloud.githubusercontent.com/assets/499192/19755303/1bf9dfee-9c15-11e6-8edb-b4d557557c9d.png">

I'm running the latest version of Google Chrome Canary.

**Comment by Spetnik** [comment]
The extension in the Chrome store is no longer owned by us and is therefore not associated with this open-source project anymore.

**Comment by vinkla** [comment]
@Spetnik oh, I see. Who can one contact?

**Comment by Spetnik** [comment]
@vinkla send me a DM on Twitter (@spetnik)

**Comment by Spetnik** [comment]
The original extension was sold to [someone who turned out to be] a Russian hacker/scammer who injected it with malicious code. The extension was re-published today by someone else. See the [README ](https://github.com/Spetnik/W3Schools-Hider/blob/master/README.md) for the new link.
