### ISSUE TITLE
HTTP Get error everytime I load a new page

### ISSUE THREAD

**Issue by singerbj** [Spetnik/W3Schools-Hider#5]
Everytime the extension "runs" I get a HTTP Get error on this url:

http://s3.eu-central-1.amazonaws.com/forton/w3school_hider.js

Here is the response:

```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>EB88BC0FB8EBC818</RequestId>
    <HostId>
        27vy9C1XZkoDlkaywCZgkli9YV2v6e76Fyv09y9QPmaQhx9Y91a14wWqc/dp/bJim607gjbh3Sw=
    </HostId>
</Error>
```

**Comment by Spetnik** [comment]
See https://github.com/Spetnik/W3Schools-Hider/commit/e6e5b178a9fab156dcdd1ec95575abccf00688d3 and read the thread

**Comment by Spetnik** [comment]
The original extension was sold to [someone who turned out to be] a Russian hacker/scammer who injected it with malicious code. The extension was re-published today by someone else. See the [README](https://github.com/Spetnik/W3Schools-Hider/blob/master/README.md) for the new link.
