### ISSUE TITLE
W3Schools Hider got flagged as malware by the Chrome Store

### ISSUE THREAD

**Issue by jespertheend** [Spetnik/W3Schools-Hider#6]
Is there any chance of this extension coming back?

**Comment by Spetnik** [comment]
The original extension was sold to [someone who turned out to be] a Russian hacker/scammer who injected it with malicious code. The extension was re-published today by someone else. See the [README ](https://github.com/Spetnik/W3Schools-Hider/blob/master/README.md) for the new link.

**Comment by jespertheend** [comment]
Alright, thanks!
